swagger: "2.0"
info:
  description: "Sample online questionarie with funny life memories"
  version: "0.1.1"
  title: "Memory Quiz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
tags:
  - name: question
    description: "Everything related to Questions"
schemes:
- "http"
paths:
  /events:
    get:
      tags:
        - question
      summary: Finds all questions
      description: "Some description"
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
definitions:
  BaseEntity:
    type: "object"
    properties:
      uuid:
        type: string
      name:
        type: string
  Event:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          groups:
            type: array
            items: 
              $ref: '#/definitions/Group'
  Group:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          contents:
            type: array
            items: 
              $ref: '#/definitions/Content'
          questions:
            type: array
            items: 
              $ref: '#/definitions/Question'
  Content:
    allOf:
      - $ref: '#/definitions/BaseEntity'
  Question:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          answers:
            type: array
            items:
              $ref: '#/definitions/Answer'
  Answer:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          exepcted:
            type: boolean