swagger: "2.0"
info:
  description: "Sample online questionarie with funny life memories"
  version: "0.1.1"
  title: "Memory Quiz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
tags:
  - name: question
    description: "Everything related to Questions"
schemes:
- "http"
paths:
  /events:
    get:
      tags:
        - question
      summary: Finds all questions
      description: "Finds all questions"
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
  /event/{uuid}:
    get:
      tags:
        - question
      summary: Return event detals
      description: "Return event detals"
      produces:
        - application/json
      parameters: 
        - 
          name: uuid
          in: path
          description: "Unique identifier of Event"
          required: true
          type: "string"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Event"
    delete:
      tags:
        - question
      description: "Deletes a new event"
      parameters: 
        - name: uuid
          in: path
          description: "Event UUID for deletion from the database"
          required: true
          type: string
      responses: 
        "200":
          description: "event response"
  /event:
    post:
      tags:
        - question
      description: "Creates a new event"
      produces: 
        - "application/json"
      parameters: 
        - 
          name: "event"
          in: "body"
          description: "Event to add to the database"
          required: true
          schema: 
            $ref: "#/definitions/Event"
      responses: 
        "200":
          description: "event response"
          schema: 
            $ref: "#/definitions/Event"
  /upload:
    post:
      tags:
        - upload
      description: "Upload image file to server"
      consumes:
        - multipart/form-data
      produces: 
        - "application/json"
      parameters:
      - name: file
        in: formData
        description: File content
        required: true
        type: file
        minLength: 1
        maxLength: 5000000  # ~5MB
      responses:
        default:
          description: Returns file location on server
          schema:
            $ref: "#/definitions/UploadLocation"
definitions:
  UploadLocation:
    type: "object"
    properties:
      url:
        type: string
  BaseEntity:
    type: "object"
    properties:
      uuid:
        type: string
      name:
        type: string
  Event:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - type: object
      - properties:
          subTitle:
            type: string
          thumbnail:
            $ref: "#/definitions/UploadLocation"
          description:
            type: string
          groups:
            type: array
            items: 
              $ref: '#/definitions/Group'
  Group:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          contents:
            type: array
            items: 
              $ref: '#/definitions/Content'
          questions:
            type: array
            items: 
              $ref: '#/definitions/Question'
  Content:
    allOf:
      - $ref: '#/definitions/BaseEntity'
  Question:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          answers:
            type: array
            items:
              $ref: '#/definitions/Answer'
  Answer:
    allOf:
      - $ref: '#/definitions/BaseEntity'
      - properties:
          exepcted:
            type: boolean